<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit014d9b31e4d4265c0ce0f4e36ff220a9
{
    public static $files = array (
        'f084d01b0a599f67676cffef638aa95b' => __DIR__ . '/..' . '/smarty/smarty/libs/bootstrap.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {

        }, null, ClassLoader::class);
    }
}
